package newpackage.view;

import javax.swing.JPanel;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import newpackage.controller.MNStatisticController;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import java.awt.Color;

public class StatisticJpanel extends JPanel {

	public StatisticJpanel() {
        initComponents();
        MNStatisticController controller = new MNStatisticController();
        controller.setDateToChart1(jpnView1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnRoot = new javax.swing.JPanel();
        jpnRoot.setBackground(Color.WHITE);
        jpnView1 = new javax.swing.JPanel();

        javax.swing.GroupLayout gl_jpnView1 = new javax.swing.GroupLayout(jpnView1);
        jpnView1.setLayout(gl_jpnView1);
        gl_jpnView1.setHorizontalGroup(
            gl_jpnView1.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 576, Short.MAX_VALUE)
        );
        gl_jpnView1.setVerticalGroup(
            gl_jpnView1.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 201, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jpnRootLayout = new javax.swing.GroupLayout(jpnRoot);
        jpnRootLayout.setHorizontalGroup(
        	jpnRootLayout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jpnRootLayout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(jpnView1, GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE)
        			.addContainerGap())
        );
        jpnRootLayout.setVerticalGroup(
        	jpnRootLayout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jpnRootLayout.createSequentialGroup()
        			.addGap(203)
        			.addComponent(jpnView1, GroupLayout.PREFERRED_SIZE, 389, GroupLayout.PREFERRED_SIZE)
        			.addGap(256))
        );
        jpnRoot.setLayout(jpnRootLayout);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnRoot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnRoot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jpnView1;
    private javax.swing.JPanel jpnRoot;
    // End of variables declaration//GEN-END:variables
}
