/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package newpackage.view;

import newpackage.controller.MNStudentController;
import newpackage.dao.StudentDAOImport;
import newpackage.model.Student;
import newpackage.until.ClassTableModel;

import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.RowSorter.SortKey;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

import com.mysql.cj.xdevapi.Table;

import javax.swing.JButton;
import javax.swing.JTable;

import java.awt.Color;
import java.awt.Font;
import java.awt.event.ActionListener;
import java.util.Date;
import java.util.List;
import java.awt.event.ActionEvent;

/**
 *
 * @author DELL
 */
public class StudentJPanel extends javax.swing.JPanel {

    /**
     * Creates new form StudentJPanel
     */
    public StudentJPanel() {
        initComponents();
        
        MNStudentController controller = new MNStudentController(jpnView, btnAdd , jtfFind);
        controller.setDateToTable();
        controller.setEvent();
    }
//    public void ReLoad() {
//    	MNStudentController controller = new MNStudentController(jpnView, btnAdd , jtfFind);
//    	controller.setDateToTable();
//    	controller.setEvent();
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnRoot = new javax.swing.JPanel();
        btnAdd = new javax.swing.JButton();
        jtfFind = new javax.swing.JTextField();
        jpnView = new javax.swing.JPanel();

        jpnRoot.setBackground(new java.awt.Color(255, 255, 255));

        btnAdd.setBackground(new java.awt.Color(0, 153, 153));
        btnAdd.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnAdd.setText("Insert");
        btnAdd.setBorder(null);
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jtfFind.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        javax.swing.GroupLayout jpnViewLayout = new javax.swing.GroupLayout(jpnView);
        jpnView.setLayout(jpnViewLayout);
        jpnViewLayout.setHorizontalGroup(
            jpnViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jpnViewLayout.setVerticalGroup(
            jpnViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 548, Short.MAX_VALUE)
        );
        
        btnSort = new JButton();
        btnSort.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		MNStudentController controller = new MNStudentController(jpnView, btnAdd , jtfFind);
    			controller.setDateToTable();
    			DefaultTableModel model = (DefaultTableModel) controller.getTable().getModel();
    			StudentDAOImport sdi = new StudentDAOImport();
				List<Student> listItem = sdi.sortList();
				String[] listColumn = {"STT" ,"Student ID" ,"Name" , "birthday" , "gender" ,"phone" , "address", "status"};
				JTable table = controller.getTable();
				TableRowSorter<TableModel> rowSorter = null;
				model = new ClassTableModel().setTableStudent(listItem, listColumn);
				table = new JTable(model);
				rowSorter = new TableRowSorter<>(table.getModel());
				table.setRowSorter(rowSorter);
				if (controller.getTable().getSelectedRow() != -1) {
					int selectdRowIndex = controller.getTable().getSelectedRow();
					selectdRowIndex = controller.getTable().convertColumnIndexToModel(selectdRowIndex);
					
					
					
					Student student = new Student();
					student.setStudent_id(model.getValueAt(selectdRowIndex, 1).toString());
					student.setName( model.getValueAt(selectdRowIndex, 2).toString());
					student.setBirthday((Date)model.getValueAt(selectdRowIndex, 3));
					student.setGender(model.getValueAt(selectdRowIndex, 4).toString());
					student.setPhone(model.getValueAt(selectdRowIndex, 5) != null ?
							model.getValueAt(selectdRowIndex, 5).toString() : null);
					student.setAddress(model.getValueAt( selectdRowIndex, 6) != null ?
							model.getValueAt(selectdRowIndex, 6).toString() : null);
					student.setStatus((boolean)model.getValueAt(selectdRowIndex, 7));
					
					
				}
				
//        		getRowSorter(treeTableModel.getRoot()).sort(true);
        	}
        });
        btnSort.setText("Sort");
        btnSort.setFont(new Font("Arial", Font.PLAIN, 18));
        btnSort.setBorder(null);
        btnSort.setBackground(new Color(0, 153, 153));

        javax.swing.GroupLayout jpnRootLayout = new javax.swing.GroupLayout(jpnRoot);
        jpnRootLayout.setHorizontalGroup(
        	jpnRootLayout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(jpnRootLayout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(jtfFind, GroupLayout.PREFERRED_SIZE, 209, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        			.addComponent(btnAdd, GroupLayout.PREFERRED_SIZE, 103, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addComponent(btnSort, GroupLayout.PREFERRED_SIZE, 102, GroupLayout.PREFERRED_SIZE)
        			.addGap(18))
        		.addComponent(jpnView, GroupLayout.DEFAULT_SIZE, 458, Short.MAX_VALUE)
        );
        jpnRootLayout.setVerticalGroup(
        	jpnRootLayout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jpnRootLayout.createSequentialGroup()
        			.addContainerGap()
        			.addGroup(jpnRootLayout.createParallelGroup(Alignment.LEADING)
        				.addGroup(jpnRootLayout.createParallelGroup(Alignment.BASELINE)
        					.addComponent(btnAdd, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE)
        					.addComponent(btnSort, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE))
        				.addComponent(jtfFind, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE))
        			.addGap(20)
        			.addComponent(jpnView, GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE))
        );
        jpnRoot.setLayout(jpnRootLayout);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addComponent(jpnRoot, GroupLayout.DEFAULT_SIZE, 467, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addComponent(jpnRoot, GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
        this.setLayout(layout);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JPanel jpnRoot;
    private javax.swing.JPanel jpnView;
    private javax.swing.JTextField jtfFind;
    private JButton btnSort;
}
